typedef struct{
    char titulo[50];
    int anio;
    char nacionalidad[50];
    int idDirector;
    int idPelicula;
    int isEmpty;
}ePelicula;
typedef struct{
    char nombre[50];
    char fechaNacimiento[12];
    char paisOrigen[50];
    int idDirector;
    int isEmpty;
}eDirector;

int initArrayPeliculas(ePelicula* pPelicula, int length);
int initArrayDirectores(eDirector* pDirector, int length);
char mostrarMenu( char textomenu[], char min, char max );
int obtenerEspacioLibre(ePelicula* pPelicula,int length);
int buscarIdPelicula(ePelicula* pPelicula, int length, int idPelicula);
void pedirDatosPelicula(ePelicula* pPelicula, int length, char* titulo,int* anio, char* Nacionalidad,int* idDirector, int* idPelicula, int pedirId);
ePelicula cargarPelicula(char auxTitulo[],int auxAnio, char auxNacionalidad[],int auxIdDirector, int auxIdPelicula);
void agregarPelicula(ePelicula* pPelicula, int length);
int isEmptyDirector(eDirector* pDirector, int length);
int isEmptyPelicula(ePelicula* pPelicula, int length);
void modificar(ePelicula* pPelicula, int length);
void borrar(ePelicula* pPelicula, int length);
int buscarNombreDirector(eDirector* pDirector, int length, char nombre[]);
int buscarIdDirector(eDirector* pDirector, int length, int idDirector);
void pedirDatosDirector(eDirector* pDirector, int lenght,char* nombre,char* fechaNacimiento,char* paisOrigen,int* idDirector);
eDirector cargarDirector(char auxNombre[],char auxFechaNacimiento[],char auxPaisOrigen[],int auxIdDirector);
int obtenerEspacioLibreDirector(eDirector* pDirector,int length);
void nuevoDirector(eDirector* pDirector, int length);
void borrarDirector(eDirector* pDirector, int length);
int cantidadPeliculasDirector(ePelicula* pPelicula, int length, int auxIdDirector);
int directorMasPeliculas(eDirector* pDirector, int lengthDirectores, ePelicula* pPelicula, int lengthPelicula);
void informar(eDirector* pDirector, int lengthDirector, ePelicula* pPelicula, int lengthPelicula);
void ordenar(ePelicula* pPelicula, int length);
void mostrarPeliculas(ePelicula* pPelicula, int length, eDirector* pDirector, int lengthDirectores);
